In [9]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("MapData.db")

In [10]:
update_query = """
UPDATE Map2526 SET fall_score = 0 WHERE fall_score IS NULL;
UPDATE MAP2425 SET fall_score = 0 WHERE fall_score IS NULL;
"""
conn.executescript(update_query)

In [11]:
select_query = """
SELECT fall_score, prior_grade, '25-26' as test_year FROM Map2526
WHERE subject='CP Algebra 2'
UNION ALL
SELECT fall_score, prior_grade, '24-25' as test_year FROM MAP2425
WHERE subject='CP Algebra 2'
ORDER by fall_score DESC
LIMIT 10;
"""

In [12]:
df = pd.read_sql_query(select_query, conn)
df

  fall_score prior_grade test_year
0        253          B+     25-26
1        249           F     25-26
2        247           B     25-26
3        241           C     25-26
4        240          A-     25-26
5        240          C+     25-26
6        237          C+     25-26
7        237           B     25-26
8        236           A     25-26
9        234          B-     25-26

In [13]:
select_query = """
SELECT fall_score, prior_grade, '25-26' as test_year FROM Map2526
WHERE subject='CP Geometry'
UNION ALL
SELECT  fall_score, prior_grade, '24-25' as test_year FROM MAP2425
WHERE subject='CP Geometry'
ORDER by fall_score DESC
LIMIT 10;
"""

In [14]:
df = pd.read_sql_query(select_query, conn)
df

  fall_score prior_grade test_year
0        243           D     25-26
1        239          A-     25-26
2        238          B-     25-26
3        235         NaN     25-26
4        230          B+     25-26
5        230          A-     25-26
6        230           C     25-26
7        229          B+     25-26
8        228          C-     25-26
9        228          C+     25-26

In [17]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("MapData.db")

In [18]:
select_query = """
SELECT fall_score, prior_grade, '25-26' as test_year FROM Map2526
WHERE subject='Honors Algebra 1'
UNION ALL
SELECT  fall_score, prior_grade, '24-25' as test_year FROM MAP2425
WHERE subject='Honors Algebra 1'
ORDER by fall_score DESC
LIMIT 10;
"""
df = pd.read_sql_query(select_query, conn)
df

  fall_score prior_grade test_year
0        290         NaN     25-26
1        281         NaN     25-26
2        248          A-     25-26
3        245          B+     25-26
4        243           A     25-26
5        242          A-     25-26
6        239          A-     25-26
7        238          B+     25-26
8        237          A-     25-26
9        232          B+     25-26

In [23]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("MapData.db")

In [24]:
query = """
SELECT subject, round(avg(fall_score), 1) as avg_fall, 
round(avg(winter_score), 1) as avg_winter,
round(avg(spring_score), 1) as avg_spring,
'25-26' as test_year FROM map2526_original
WHERE subject is NOT NULL
GROUP by subject
UNION ALL
SELECT subject, round(avg(fall_score),1) as avg_fall,
round(avg(winter_score), 1) as avg_winter,
round(avg(spring_score), 1) as avg_spring,
 '24-25' as test_year FROM map2425_original
WHERE subject is NOT NULL
GROUP by subject
ORDER by subject;
"""
df = pd.read_sql_query(query, conn)
df

            subject  avg_fall  avg_winter  avg_spring test_year
0      CP Algebra 2     233.8       230.6       235.5     25-26
1       CP Geometry     220.0       222.6       229.6     25-26
2  Honors Algebra 1     241.9       244.3       243.6     25-26
3  Honors Algebra 1     232.6       235.8       236.9     24-25

In [ ]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("MapData.db")

In [27]:
query = """
SELECT round((average_student_score/10 * 10)) || '-' || round((average_student_score/10 * 10 + 9)) as avg_score_range, count(*) as student_count
FROM (
SELECT
round((coalesce(fall_score, 0) + coalesce(winter_score, 0) + coalesce(spring_score, 0)) / ((fall_score is NOT NULL) + (winter_score is NOT NULL) + (spring_score is
 NOT NULL))) as average_student_score
 FROM map2526_original
UNION ALL
SELECT
round((coalesce(fall_score, 0) + coalesce(winter_score, 0) + coalesce(spring_score, 0)) / ((fall_score is NOT NULL) + (winter_score is NOT NULL) + (spring_score is
 NOT NULL))) as average_student_score
 FROM map2425_original
)
WHERE average_student_score is NOT NULL
GROUP by round((average_student_score/10))
ORDER by average_student_score

"""
df = pd.read_sql_query(query, conn)
df

  avg_score_range  student_count
0     201.0-210.0              3
1     211.0-220.0              7
2     218.0-227.0             20
3     226.0-235.0             27
4     236.0-245.0             21
5     249.0-258.0              7
6     255.0-264.0              4
7     270.0-279.0              1
8     282.0-291.0              1
9     295.0-304.0              1

In [33]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("MapData.db")

In [34]:
query = """
SELECT subject, (average_student_score/10*10) ||'-'|| (average_student_score/10*10 + 9) as avg_score_range, count(*) as student_count
FROM (
SELECT
subject, round((coalesce(fall_score, 0) + coalesce(winter_score, 0) + coalesce(spring_score, 0)) / ((fall_score is NOT NULL) + (winter_score is NOT NULL) + (spring_score is
 NOT NULL))) as average_student_score
 FROM map2526_original
UNION ALL
SELECT
subject, round((coalesce(fall_score, 0) + coalesce(winter_score, 0) + coalesce(spring_score, 0)) / ((fall_score is NOT NULL) + (winter_score is NOT NULL) + (spring_score is
 NOT NULL))) as average_student_score
 FROM map2425_original
)
WHERE average_student_score is NOT NULL
GROUP by subject, round(average_student_score /10)
HAVING subject is NOT NULL
ORDER by average_student_score
"""
df = pd.read_sql_query(query, conn)
df

             subject avg_score_range  student_count
0        CP Geometry     201.0-210.0              3
1        CP Geometry     211.0-220.0              7
2       CP Algebra 2     218.0-227.0              5
3        CP Geometry     223.0-232.0             12
4   Honors Algebra 1     223.0-232.0              3
5       CP Algebra 2     226.0-235.0              6
6        CP Geometry     227.0-236.0             11
7   Honors Algebra 1     230.0-239.0             10
8       CP Algebra 2     236.0-245.0              4
9        CP Geometry     237.0-246.0              4
10  Honors Algebra 1     243.0-252.0             13
11  Honors Algebra 1     245.0-254.0              3
12      CP Algebra 2     249.0-258.0              2
13      CP Algebra 2     255.0-264.0              1
14  Honors Algebra 1     259.0-268.0              2
15  Honors Algebra 1     282.0-291.0              1
16  Honors Algebra 1     295.0-304.0              1

In [40]:
query = """
SELECT subject, prior_subject,
CASE
	WHEN subject = 'Honors Algebra 1' THEN spring_score
	ELSE fall_score
END as honors_score
FROM map2526_original
WHERE (subject = 'Honors Algebra 1' or prior_subject = 'Honors Algebra 1' or prior_subject = 'Honors Geometry' or prior_subject = 'Honors Algebra 2')
	AND honors_score is NOT NULL

UNION ALL

SELECT subject, prior_subject,
CASE
	WHEN subject = 'Honors Algebra 1' THEN spring_score
	ELSE fall_score
END as honors_score
FROM map2425_original
WHERE (subject = 'Honors Algebra 1' or prior_subject = 'Honors Algebra 1' or prior_subject = 'Honors Geometry' or prior_subject = 'Honors Algebra 2')
	AND honors_score is NOT NULL
ORDER by subject, honors_score DESC, prior_subject
;
"""
df = pd.read_sql_query(query, conn)
df

             subject        prior_subject honors_score
0       CP Algebra 2      Honors Geometry          253
1       CP Algebra 2     Honors Algebra 2          249
2       CP Algebra 2      Honors Geometry          247
3       CP Algebra 2      Honors Geometry          240
4        CP Geometry     Honors Algebra 1          243
5        CP Geometry     Honors Algebra 1          239
6        CP Geometry     Honors Algebra 1          230
7        CP Geometry     Honors Algebra 1          230
8        CP Geometry     Honors Algebra 1          228
9        CP Geometry     Honors Algebra 1          224
10       CP Geometry     Honors Algebra 1          219
11       CP Geometry     Honors Algebra 1          218
12  Honors Algebra 1                  NaN          290
13  Honors Algebra 1  Concepts of Algebra          254
14  Honors Algebra 1  Concepts of Algebra          244
15  Honors Algebra 1  Concepts of Algebra          243
16  Honors Algebra 1  Concepts of Algebra          229
17  Honors Algebra 1  Concepts of Algebra          224
18  Honors Algebra 1  Concepts of Algebra          221
19  Honors Algebra 1  Concepts of Algebra          263
20  Honors Algebra 1  Concepts of Algebra          247
21  Honors Algebra 1                  NaN          245
22  Honors Algebra 1  Concepts of Algebra          245
23  Honors Algebra 1  Concepts of Algebra          242
24  Honors Algebra 1  Concepts of Algebra          241
25  Honors Algebra 1                  NaN          240
26  Honors Algebra 1  Concepts of Algebra          240
27  Honors Algebra 1  Concepts of Algebra          238
28  Honors Algebra 1  Concepts of Algebra          236
29  Honors Algebra 1  Concepts of Algebra          234
30  Honors Algebra 1  Concepts of Algebra          231
31  Honors Algebra 1  Concepts of Algebra          229
32  Honors Algebra 1  Concepts of Algebra          222
33  Honors Algebra 1  Concepts of Algebra          220
34  Honors Algebra 1  Concepts of Algebra          218

In [45]:
query = """
SELECT subject, prior_subject, 
max(ifnull(fall_score, 0), ifnull(winter_score, 0), ifnull(spring_score, 0)) as max_score
FROM map2526_original
WHERE (subject = 'CP Geometry' or subject = 'CP Algebra 2')
	AND (prior_subject = 'CP Algebra 1' or prior_subject = 'CP Geometry' or prior_subject = 'CP Algebra 2' or prior_subject = 'Concepts of Algebra')
GROUP by max_score

UNION ALL

SELECT subject, prior_subject, 
max(ifnull(fall_score, 0), ifnull(winter_score, 0), ifnull(spring_score, 0)) as max_score
FROM map2425_original
WHERE (subject = 'CP Geometry' or subject = 'CP Algebra 2')
	AND (prior_subject = 'CP Algebra 1' or prior_subject = 'CP Geometry' or prior_subject = 'CP Algebra 2' or prior_subject = 'Concepts of Algebra')
GROUP by max_score
ORDER by subject,  max_score DESC, prior_subject
;
"""
df = pd.read_sql_query(query, conn)
df

         subject prior_subject max_score
0   CP Algebra 2   CP Geometry       241
1   CP Algebra 2   CP Geometry       240
2   CP Algebra 2   CP Geometry       239
3   CP Algebra 2   CP Geometry       237
4   CP Algebra 2  CP Algebra 1       236
5   CP Algebra 2   CP Geometry       233
6   CP Algebra 2   CP Geometry       232
7   CP Algebra 2   CP Geometry       228
8   CP Algebra 2   CP Geometry       224
9   CP Algebra 2   CP Geometry       223
10  CP Algebra 2   CP Geometry       222
11  CP Algebra 2   CP Geometry       217
12  CP Algebra 2   CP Geometry         0
13   CP Geometry  CP Algebra 1       248
14   CP Geometry  CP Algebra 1       230
15   CP Geometry  CP Algebra 1       229
16   CP Geometry  CP Algebra 1       227
17   CP Geometry  CP Algebra 1       226
18   CP Geometry   CP Geometry       225
19   CP Geometry  CP Algebra 1       218
20   CP Geometry  CP Algebra 1       216
21   CP Geometry   CP Geometry       214
22   CP Geometry  CP Algebra 1       213
23   CP Geometry  CP Algebra 1       212
24   CP Geometry  CP Algebra 1       208
25   CP Geometry  CP Algebra 1       205
26   CP Geometry  CP Algebra 1       203

In [49]:
query = """
SELECT id, subject,
coalesce(CASE
	WHEN ifnull(fall_score, 0) >= ifnull(winter_score, 0) 
		AND ifnull(fall_score, 0) >= ifnull(spring_score, 0)
		THEN fall_score
	WHEN ifnull(winter_score, 0) >= ifnull(fall_score, 0) 
		AND ifnull(winter_score, 0) >= ifnull(spring_score, 0)
		THEN winter_score
	ELSE ifnull(spring_score, 0)
END, 0)
-
coalesce(CASE
	WHEN fall_score is NOT NULL
		AND (winter_score is NULL or fall_score <= winter_score)
		AND (spring_score is NULL or fall_score <= spring_score)
		THEN fall_score
	WHEN winter_score is NOT NULL
		AND (fall_score is NULL or winter_score <= fall_score)
		AND (spring_score is NULL or winter_score <= spring_score)
		THEN winter_score
	WHEN spring_score is NOT NULL
		THEN spring_score
	ELSE NULL
END, 0) as improvement
FROM map2526_original
WHERE id is NOT NULL and subject = 'CP Algebra 2' AND improvement > 1

UNION ALL

SELECT id, ifnull(subject, 'Mixed Course') as subject,
coalesce(CASE
	WHEN ifnull(fall_score, 0) >= ifnull(winter_score, 0) 
		AND ifnull(fall_score, 0) >= ifnull(spring_score, 0)
		THEN fall_score
	WHEN ifnull(winter_score, 0) >= ifnull(fall_score, 0) 
		AND ifnull(winter_score, 0) >= ifnull(spring_score, 0)
		THEN winter_score
	ELSE ifnull(spring_score, 0)
END, 0)
-
coalesce(CASE
	WHEN fall_score is NOT NULL
		AND (winter_score is NULL or fall_score <= winter_score)
		AND (spring_score is NULL or fall_score <= spring_score)
		THEN fall_score
	WHEN winter_score is NOT NULL
		AND (fall_score is NULL or winter_score <= fall_score)
		AND (spring_score is NULL or winter_score <= spring_score)
		THEN winter_score
	WHEN spring_score is NOT NULL
		THEN spring_score
	ELSE NULL
END, 0) as improvement
FROM map2425_original
WHERE id is NOT NULL and subject = 'CP Algebra 2' AND improvement > 1

ORDER by subject, improvement DESC;
"""
df = pd.read_sql_query(query, conn)
df

    id       subject  improvement
0  OLJ  CP Algebra 2           20
1  ABD  CP Algebra 2           18
2   AA  CP Algebra 2            8
3  MFW  CP Algebra 2            7
4   UH  CP Algebra 2            7
5  ABK  CP Algebra 2            5
6   AJ  CP Algebra 2            4
7   IJ  CP Algebra 2            4
8  RRR  CP Algebra 2            3

In [50]:
query = """
SELECT id, subject,
coalesce(CASE
	WHEN ifnull(fall_score, 0) >= ifnull(winter_score, 0) 
		AND ifnull(fall_score, 0) >= ifnull(spring_score, 0)
		THEN fall_score
	WHEN ifnull(winter_score, 0) >= ifnull(fall_score, 0) 
		AND ifnull(winter_score, 0) >= ifnull(spring_score, 0)
		THEN winter_score
	ELSE ifnull(spring_score, 0)
END, 0)
-
coalesce(CASE
	WHEN fall_score is NOT NULL
		AND (winter_score is NULL or fall_score <= winter_score)
		AND (spring_score is NULL or fall_score <= spring_score)
		THEN fall_score
	WHEN winter_score is NOT NULL
		AND (fall_score is NULL or winter_score <= fall_score)
		AND (spring_score is NULL or winter_score <= spring_score)
		THEN winter_score
	WHEN spring_score is NOT NULL
		THEN spring_score
	ELSE NULL
END, 0) as improvement
FROM map2526_original
WHERE id is NOT NULL and subject = 'CP Geometry' AND improvement > 1

UNION ALL

SELECT id, ifnull(subject, 'Mixed Course') as subject,
coalesce(CASE
	WHEN ifnull(fall_score, 0) >= ifnull(winter_score, 0) 
		AND ifnull(fall_score, 0) >= ifnull(spring_score, 0)
		THEN fall_score
	WHEN ifnull(winter_score, 0) >= ifnull(fall_score, 0) 
		AND ifnull(winter_score, 0) >= ifnull(spring_score, 0)
		THEN winter_score
	ELSE ifnull(spring_score, 0)
END, 0)
-
coalesce(CASE
	WHEN fall_score is NOT NULL
		AND (winter_score is NULL or fall_score <= winter_score)
		AND (spring_score is NULL or fall_score <= spring_score)
		THEN fall_score
	WHEN winter_score is NOT NULL
		AND (fall_score is NULL or winter_score <= fall_score)
		AND (spring_score is NULL or winter_score <= spring_score)
		THEN winter_score
	WHEN spring_score is NOT NULL
		THEN spring_score
	ELSE NULL
END, 0) as improvement
FROM map2425_original
WHERE id is NOT NULL and subject = 'CP Geometry' AND improvement > 1

ORDER by subject, improvement DESC;
"""
df = pd.read_sql_query(query, conn)
df

     id      subject  improvement
0    VJ  CP Geometry           18
1    AA  CP Geometry           16
2    MK  CP Geometry           14
3    FM  CP Geometry           13
4   MNM  CP Geometry           11
5   DJB  CP Geometry           10
6    AM  CP Geometry           10
7   AMJ  CP Geometry           10
8    FJ  CP Geometry           10
9    AS  CP Geometry            9
10   TD  CP Geometry            9
11  SMA  CP Geometry            8
12   HX  CP Geometry            7
13   SD  CP Geometry            7
14  JAB  CP Geometry            6
15  RVI  CP Geometry            5
16   JJ  CP Geometry            4
17   NE  CP Geometry            4
18   SB  CP Geometry            4
19   AZ  CP Geometry            4
20   AR  CP Geometry            4
21   CA  CP Geometry            4
22  EHS  CP Geometry            4
23   PM  CP Geometry            4
24   PR  CP Geometry            3
25  GCE  CP Geometry            3
26   SA  CP Geometry            2
27   CK  CP Geometry            2
28   FN  CP Geometry            2
29   PA  CP Geometry            2

In [51]:
query = """
SELECT id, subject,
coalesce(CASE
	WHEN ifnull(fall_score, 0) >= ifnull(winter_score, 0) 
		AND ifnull(fall_score, 0) >= ifnull(spring_score, 0)
		THEN fall_score
	WHEN ifnull(winter_score, 0) >= ifnull(fall_score, 0) 
		AND ifnull(winter_score, 0) >= ifnull(spring_score, 0)
		THEN winter_score
	ELSE ifnull(spring_score, 0)
END, 0)
-
coalesce(CASE
	WHEN fall_score is NOT NULL
		AND (winter_score is NULL or fall_score <= winter_score)
		AND (spring_score is NULL or fall_score <= spring_score)
		THEN fall_score
	WHEN winter_score is NOT NULL
		AND (fall_score is NULL or winter_score <= fall_score)
		AND (spring_score is NULL or winter_score <= spring_score)
		THEN winter_score
	WHEN spring_score is NOT NULL
		THEN spring_score
	ELSE NULL
END, 0) as improvement
FROM map2526_original
WHERE id is NOT NULL and subject = 'Honors Algebra 1' AND improvement > 1

UNION ALL

SELECT id, ifnull(subject, 'Mixed Course') as subject,
coalesce(CASE
	WHEN ifnull(fall_score, 0) >= ifnull(winter_score, 0) 
		AND ifnull(fall_score, 0) >= ifnull(spring_score, 0)
		THEN fall_score
	WHEN ifnull(winter_score, 0) >= ifnull(fall_score, 0) 
		AND ifnull(winter_score, 0) >= ifnull(spring_score, 0)
		THEN winter_score
	ELSE ifnull(spring_score, 0)
END, 0)
-
coalesce(CASE
	WHEN fall_score is NOT NULL
		AND (winter_score is NULL or fall_score <= winter_score)
		AND (spring_score is NULL or fall_score <= spring_score)
		THEN fall_score
	WHEN winter_score is NOT NULL
		AND (fall_score is NULL or winter_score <= fall_score)
		AND (spring_score is NULL or winter_score <= spring_score)
		THEN winter_score
	WHEN spring_score is NOT NULL
		THEN spring_score
	ELSE NULL
END, 0) as improvement
FROM map2425_original
WHERE id is NOT NULL and subject = 'Honors Algebra 1' AND improvement > 1

ORDER by subject, improvement DESC;
"""
df = pd.read_sql_query(query, conn)
df

     id           subject  improvement
0   JDC  Honors Algebra 1           18
1   VSL  Honors Algebra 1           17
2    TS  Honors Algebra 1           16
3    PC  Honors Algebra 1           14
4    BL  Honors Algebra 1           14
5    CD  Honors Algebra 1           13
6    ZA  Honors Algebra 1           12
7    TM  Honors Algebra 1           11
8    AI  Honors Algebra 1           10
9   CSD  Honors Algebra 1           10
10   OJ  Honors Algebra 1           10
11   AC  Honors Algebra 1            9
12   PA  Honors Algebra 1            9
13  PMD  Honors Algebra 1            7
14   AB  Honors Algebra 1            7
15   LJ  Honors Algebra 1            7
16   RJ  Honors Algebra 1            7
17   IO  Honors Algebra 1            6
18  VSB  Honors Algebra 1            6
19  MTA  Honors Algebra 1            5
20   BK  Honors Algebra 1            4
21  FHX  Honors Algebra 1            4
22   RL  Honors Algebra 1            4
23   RA  Honors Algebra 1            4
24  FNK  Honors Algebra 1            4
25   PK  Honors Algebra 1            3
26   ES  Honors Algebra 1            2
27   DE  Honors Algebra 1            2

In [52]:
query = """
SELECT round(avg(fall_score), 1) as avg_fall, 
round(avg(winter_score), 1) as avg_winter,
round(avg(spring_score), 1) as avg_spring,
'25-26' as test_year FROM map2526_original

UNION ALL

SELECT round(avg(fall_score),1) as avg_fall,
round(avg(winter_score), 1) as avg_winter,
round(avg(spring_score), 1) as avg_spring,
 '24-25' as test_year FROM map2425_original

 ORDER by test_year;
 """
df = pd.read_sql_query(query, conn)
df

   avg_fall  avg_winter  avg_spring test_year
0     232.6       235.8       236.9     24-25
1     228.2       230.1       240.4     25-26

In [53]:
query = """
SELECT round(avg(fall_score), 1) as avg_fall, 
round(avg(fall_percentile), 1) as avg_fall_percentile,
round(avg(winter_score), 1) as avg_winter,
round(avg(winter_percentile), 1) as avg_winter_percentile,
round(avg(spring_score), 1) as avg_spring,
round(avg(spring_percentile), 1) as avg_spring_percentile
FROM map2526_original
"""
df = pd.read_sql_query(query, conn)
df

,avg_fall,avg_fall_percentile,avg_winter,avg_winter_percentile,avg_spring,avg_spring_percentile
0,228.2,39.0,230.1,35.9,240.4,46.5

In [63]:
query = """
SELECT count(*) as fall_count,
CASE
	WHEN fall_score = 0 THEN 'NO SCORE'
    WHEN fall_score <= 200 AND fall_score > 0 THEN 'RED'
	WHEN fall_score > 200 AND fall_score <= 220 THEN 'ORANGE'
	WHEN fall_score > 220 AND fall_score <= 240 THEN 'YELLOW'
	WHEN fall_score > 240 AND fall_score <= 260 THEN 'GREEN'
	ELSE 'BLUE'
END as fall_category

FROM Map2526

GROUP by fall_category
ORDER by
	CASE fall_category
		WHEN 'BLUE' THEN 1
		WHEN 'GREEN' THEN 2
		WHEN 'YELLOW' THEN 3
		WHEN 'ORANGE' THEN 4
        WHEN 'RED' THEN 5
		ELSE 6
	END;
"""

df = pd.read_sql_query(query, conn)
df

   fall_count fall_category
0           2          BLUE
1           9         GREEN
2          37        YELLOW
3          22        ORANGE
4          14      NO SCORE

In [64]:
query = """
SELECT count(*) as winter_count,
CASE
	WHEN winter_score = 0 THEN 'NO SCORE'
    WHEN winter_score <= 200 AND winter_score > 0 THEN 'RED'
	WHEN winter_score > 200 AND winter_score <= 220 THEN 'ORANGE'
	WHEN winter_score > 220 AND winter_score <= 240 THEN 'YELLOW'
	WHEN winter_score > 240 AND winter_score <= 260 THEN 'GREEN'
	ELSE 'BLUE'
END as winter_category

FROM Map2526

GROUP by winter_category
ORDER by
	CASE winter_category
		WHEN 'BLUE' THEN 1
		WHEN 'GREEN' THEN 2
		WHEN 'YELLOW' THEN 3
		WHEN 'ORANGE' THEN 4
        WHEN 'RED' THEN 5
		ELSE 6
	END;
"""

df = pd.read_sql_query(query, conn)
df

   winter_count winter_category
0             3            BLUE
1             9           GREEN
2            32          YELLOW
3            15          ORANGE
4             1             RED
5            24        NO SCORE

In [61]:
query = """
SELECT count(*) as spring_count,
CASE
	WHEN spring_score <= 200 AND spring_score > 0 THEN 'RED'
	WHEN spring_score > 200 AND spring_score <= 220 THEN 'ORANGE'
	WHEN spring_score > 220 AND spring_score <= 240 THEN 'YELLOW'
	WHEN spring_score > 240 AND spring_score <= 260 THEN 'GREEN'
    WHEN spring_score > 260 THEN 'BLUE'
	ELSE 'NO SCORE'
END as spring_category

FROM Map2526

GROUP by spring_category
ORDER by
	CASE spring_category
		WHEN 'BLUE' THEN 1
		WHEN 'GREEN' THEN 2
		WHEN 'YELLOW' THEN 3
		WHEN 'ORANGE' THEN 4
		WHEN 'RED' THEN 5
        ELSE 6
	END;
"""

df = pd.read_sql_query(query, conn)
df

   spring_count spring_category
0             3            BLUE
1             8           GREEN
2            10          YELLOW
3             1          ORANGE
4            62        NO SCORE

In [65]:
query = """
SELECT fall_score, winter_score,
CASE
	WHEN fall_score <> winter_score THEN winter_score - fall_score
	WHEN fall_score = winter_score THEN 0
	ELSE NULL
END as improvement
FROM map2526_original
WHERE improvement is NOT NULL
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

   fall_score winter_score  improvement
0         230          246           16
1         212          226           14
2         212          225           13
3         225          237           12
4         290          301           11
5         218          228           10
6         208          218           10
7         224          233            9
8         222          230            8
9         223          230            7
10        218          225            7
11        215          222            7
12        232          239            7
13        247          252            5
14        253          257            4
15        209          213            4
16        228          232            4
17        224          228            4
18        222          226            4
19        230          234            4
20        242          246            4
21        226          229            3
22        226          229            3
23        216          218            2
24        216          218            2
25        212          214            2
26        210          212            2
27        243          245            2
28        239          241            2
29        238          239            1
30        216          217            1
31        236          236            0
32        214          213           -1
33        205          204           -1
34        229          228           -1
35        218          216           -2
36        233          230           -3
37        203          200           -3
38        228          224           -4
39        216          212           -4
40        230          226           -4
41        208          204           -4
42        245          241           -4
43        225          221           -4
44        237          232           -5
45        239          234           -5
46        228          223           -5
47        281          276           -5
48        223          217           -6
49        248          242           -6
50        229          222           -7
51        229          222           -7
52        222          214           -8
53        243          232          -11
54        235          219          -16
55        240          222          -18
56        241          221          -20

In [68]:
update_query = """
ALTER TABLE Map2526
    ADD improvement INT;
    
UPDATE Map2526
	SET improvement = winter_score - fall_score
	WHERE fall_score <> winter_score;
	
UPDATE Map2526
	SET improvement = 0
	WHERE fall_score = winter_score;

UPDATE Map2526
	SET improvement = NULL
	WHERE fall_score =0 or winter_score = 0;
"""
conn.executescript(update_query)

In [70]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'Significant'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

    improvement     category
0            16  Significant
1            14  Significant
2            13  Significant
3            12  Significant
4            11  Significant
5            10  Significant
6            10  Significant
7             9  Significant
8             8  Significant
9             7  Significant
10            7  Significant
11            7  Significant
12            7  Significant
13            5  Significant

In [71]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'Slight'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

    improvement category
0           4.0   Slight
1           4.0   Slight
2           4.0   Slight
3           4.0   Slight
4           4.0   Slight
5           4.0   Slight
6           4.0   Slight
7           3.0   Slight
8           3.0   Slight
9           2.0   Slight
10          2.0   Slight
11          2.0   Slight
12          2.0   Slight
13          2.0   Slight
14          2.0   Slight
15          1.0   Slight
16          1.0   Slight
17          NaN   Slight
18          NaN   Slight
19          NaN   Slight
20          NaN   Slight
21          NaN   Slight
22          NaN   Slight
23          NaN   Slight
24          NaN   Slight
25          NaN   Slight
26          NaN   Slight
27          NaN   Slight
28          NaN   Slight
29          NaN   Slight
30          NaN   Slight
31          NaN   Slight
32          NaN   Slight
33          NaN   Slight
34          NaN   Slight
35          NaN   Slight
36          NaN   Slight
37          NaN   Slight
38          NaN   Slight
39          NaN   Slight
40          NaN   Slight
41          NaN   Slight
42          NaN   Slight
43          NaN   Slight

In [72]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'None'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

   improvement category
0            0     None

In [73]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'Decreased'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

    improvement   category
0            -1  Decreased
1            -1  Decreased
2            -1  Decreased
3            -2  Decreased
4            -3  Decreased
5            -3  Decreased
6            -4  Decreased
7            -4  Decreased
8            -4  Decreased
9            -4  Decreased
10           -4  Decreased
11           -4  Decreased
12           -5  Decreased
13           -5  Decreased
14           -5  Decreased
15           -5  Decreased
16           -6  Decreased
17           -6  Decreased
18           -7  Decreased
19           -7  Decreased
20           -8  Decreased
21          -11  Decreased
22          -16  Decreased
23          -18  Decreased
24          -20  Decreased

In [74]:
update_query = """

UPDATE Map2526
	SET improvement = spring_score - winter_score
	WHERE spring_score <> winter_score;
	
UPDATE Map2526
	SET improvement = 0
	WHERE spring_score = winter_score;

UPDATE Map2526
	SET improvement = NULL
	WHERE spring_score = 0 or winter_score = 0;
"""
conn.executescript(update_query)

In [75]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'Significant'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

   improvement     category
0           14  Significant
1           10  Significant
2            7  Significant
3            5  Significant

In [77]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'Slight' and improvement is not null
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

   improvement category
0            3   Slight
1            2   Slight
2            2   Slight
3            2   Slight
4            2   Slight
5            2   Slight
6            2   Slight
7            1   Slight

In [78]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'None'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

   improvement category
0            0     None
1            0     None
2            0     None

In [79]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'Decreased'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

   improvement   category
0           -2  Decreased
1           -5  Decreased
2          -18  Decreased

In [80]:
update_query = """

UPDATE Map2526
	SET improvement = spring_score - fall_score
	WHERE spring_score <> fall_score;
	
UPDATE Map2526
	SET improvement = 0
	WHERE spring_score = fall_score;

UPDATE Map2526
	SET improvement = NULL
	WHERE spring_score = 0 or fall_score = 0;
"""
conn.executescript(update_query)

In [81]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'Significant'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

   improvement     category
0           18  Significant
1           16  Significant
2           14  Significant
3           10  Significant
4            9  Significant
5            9  Significant
6            7  Significant
7            5  Significant
8            5  Significant

In [83]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'Slight' and improvement is not null
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

   improvement category
0            4   Slight
1            4   Slight
2            3   Slight
3            2   Slight
4            2   Slight

In [84]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'None'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

Empty DataFrame
Columns: [improvement, category]
Index: []

In [85]:
query = """
SELECT improvement,

CASE
	WHEN improvement >= 5 THEN 'Significant'
	WHEN improvement = 0 THEN 'None'
	WHEN improvement < 0 THEN 'Decreased'
	ELSE 'Slight'
END as category

FROM Map2526
where category = 'Decreased'
ORDER by improvement DESC
"""
df = pd.read_sql_query(query, conn)
df

   improvement   category
0           -5  Decreased
1           -5  Decreased
2          -11  Decreased
3          -18  Decreased

In [95]:
query = """
SELECT 
coalesce(
CASE
	WHEN spring_score is NOT NULL
		THEN spring_score
	WHEN spring_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 1000
END, 0)
-
coalesce(
CASE
	WHEN fall_score is NOT NULL
		THEN fall_score
	WHEN fall_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 0
END, 0) as score_change
FROM map2526_original
WHERE score_change > 0 and score_change < 200
ORDER by score_change DESC;	
"""

df = pd.read_sql_query(query, conn)
df

    score_change
0             18
1             16
2             14
3             13
4             12
5             11
6             10
7             10
8              9
9              9
10             9
11             8
12             7
13             7
14             5
15             5
16             5
17             4
18             4
19             4
20             4
21             4
22             4
23             4
24             3
25             3
26             2
27             2
28             2
29             2
30             2
31             2
32             1
33             1
34             1

In [96]:
query = """
SELECT 
coalesce(
CASE
	WHEN spring_score is NOT NULL
		THEN spring_score
	WHEN spring_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 1000
END, 0)
-
coalesce(
CASE
	WHEN fall_score is NOT NULL
		THEN fall_score
	WHEN fall_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 0
END, 0) as score_change
FROM map2526_original
WHERE score_change = 0
ORDER by score_change DESC;	
"""

df = pd.read_sql_query(query, conn)
df

   score_change
0             0
1             0
2             0

In [97]:
query = """
SELECT 
coalesce(
CASE
	WHEN spring_score is NOT NULL
		THEN spring_score
	WHEN spring_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 1000
END, 0)
-
coalesce(
CASE
	WHEN fall_score is NOT NULL
		THEN fall_score
	WHEN fall_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 0
END, 0) as score_change
FROM map2526_original
WHERE score_change < 0
ORDER by score_change DESC;	
"""

df = pd.read_sql_query(query, conn)
df

    score_change
0             -1
1             -1
2             -1
3             -2
4             -3
5             -3
6             -4
7             -4
8             -4
9             -4
10            -4
11            -4
12            -5
13            -5
14            -5
15            -6
16            -6
17            -8
18           -11
19           -11
20           -16
21           -18
22           -18

In [103]:
query = """
SELECT id,
coalesce(
CASE
	WHEN spring_score is NOT NULL
		THEN spring_score
	WHEN spring_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 1000
END, 0)
-
coalesce(
CASE
	WHEN fall_score is NOT NULL
		THEN fall_score
	WHEN fall_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 0
END, 0) as score_change,
CASE
	WHEN spring_percentile is NULL THEN winter_percentile
	WHEN winter_percentile is NULL AND spring_percentile is NULL THEN fall_percentile
	ELSE spring_percentile
END as growth_percentile
FROM map2526_original
WHERE score_change < 200 and CAST(growth_percentile as INTEGER) <= 6
ORDER by CAST(growth_percentile as INTEGER) DESC, score_change DESC;
"""
df = pd.read_sql_query(query, conn)
df

    id  score_change growth_percentile
0   AA            -8                 5
1   JC            -1                 3
2   PM            -4                 3
3  GCE            -3                 2

In [110]:
query = """
SELECT id,
coalesce(
CASE
	WHEN spring_score is NOT NULL
		THEN spring_score
	WHEN spring_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 1000
END, 0)
-
coalesce(
CASE
	WHEN fall_score is NOT NULL
		THEN fall_score
	WHEN fall_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 0
END, 0) as score_change,
CASE
	WHEN spring_percentile is NULL THEN winter_percentile
	WHEN winter_percentile is NULL AND spring_percentile is NULL THEN fall_percentile
	ELSE spring_percentile
END as growth_percentile
FROM map2526_original
WHERE score_change < 200 and CAST(growth_percentile as INTEGER) <= 27 and CAST(growth_percentile as INTEGER) > 6
ORDER by score_change DESC;
"""
df = pd.read_sql_query(query, conn)
df

     id  score_change growth_percentile
0    MK            14                24
1    FM            13                27
2   AMJ            10                23
3    AS             9                26
4   MFW             7                11
5    FJ             5                 9
6    JJ             4                10
7    SA             2                16
8    CK             2                11
9    FN             2                 9
10   AZ             1                14
11   VD            -1                10
12   PA            -2                13
13  RRR            -3                22
14   AJ            -4                14
15   SB            -4                 9
16   RA            -4                25
17  RVI            -5                24
18   SD            -5                21
19  PMD            -5                26
20  JAB            -6                14
21  JDC           -11                21
22   AA           -16                17
23  ABD           -18                12
24  OLJ           -18                11

In [109]:
query = """
SELECT id,
coalesce(
CASE
	WHEN spring_score is NOT NULL
		THEN spring_score
	WHEN spring_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 1000
END, 0)
-
coalesce(
CASE
	WHEN fall_score is NOT NULL
		THEN fall_score
	WHEN fall_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 0
END, 0) as score_change,
CASE
	WHEN spring_percentile is NULL THEN winter_percentile
	WHEN winter_percentile is NULL AND spring_percentile is NULL THEN fall_percentile
	ELSE spring_percentile
END as growth_percentile
FROM map2526_original
WHERE score_change < 200 and CAST(growth_percentile as INTEGER) <= 63 and CAST(growth_percentile as INTEGER) > 27
ORDER by score_change DESC;
"""
df = pd.read_sql_query(query, conn)
df

     id  score_change growth_percentile
0    ZA            12                59
1   DJB            10                33
2    TD             9                45
3   SMA             8                38
4    HX             7                38
5    AM             5                60
6    NE             4                42
7    AZ             4                33
8    CA             4                29
9   EHS             4                47
10  FHX             4                62
11   PR             3                36
12   PK             3                34
13   UH             2                34
14  NPC             1                58
15   MN             0                33
16  REN             0                61
17   SM            -1                39
18   AR            -4                29
19  MNM           -11                42

In [108]:
query = """
SELECT id,
coalesce(
CASE
	WHEN spring_score is NOT NULL
		THEN spring_score
	WHEN spring_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 1000
END, 0)
-
coalesce(
CASE
	WHEN fall_score is NOT NULL
		THEN fall_score
	WHEN fall_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 0
END, 0) as score_change,
CASE
	WHEN spring_percentile is NULL THEN winter_percentile
	WHEN winter_percentile is NULL AND spring_percentile is NULL THEN fall_percentile
	ELSE spring_percentile
END as growth_percentile
FROM map2526_original
WHERE score_change < 200 and CAST(growth_percentile as INTEGER) <= 89 and CAST(growth_percentile as INTEGER) > 63
ORDER by score_change DESC;
"""
df = pd.read_sql_query(query, conn)
df

    id  score_change growth_percentile
0   VJ            18                67
1   TS            16                81
2  ABK             5                66
3   IJ             4                70
4   ES             2                75
5   RL             2                64
6  SAK             1                89
7   BK            -4                67
8   IO            -6                69

In [107]:
query = """
SELECT id,
coalesce(
CASE
	WHEN spring_score is NOT NULL
		THEN spring_score
	WHEN spring_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 1000
END, 0)
-
coalesce(
CASE
	WHEN fall_score is NOT NULL
		THEN fall_score
	WHEN fall_score is NULL
		AND winter_score is NOT NULL
		THEN winter_score
	ELSE 0
END, 0) as score_change,
CASE
	WHEN spring_percentile is NULL THEN winter_percentile
	WHEN winter_percentile is NULL AND spring_percentile is NULL THEN fall_percentile
	ELSE spring_percentile
END as growth_percentile
FROM map2526_original
WHERE score_change < 200 and CAST(growth_percentile as INTEGER) > 89
ORDER by CAST(growth_percentile as INTEGER) DESC, score_change DESC;
"""
df = pd.read_sql_query(query, conn)
df

   id  score_change growth_percentile
0  TM            11                99
1  PC             9                99
2  CE             0                93